# Generated by Django 4.1.3 on 2022-11-27 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('dorm_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('dorm_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('team_pic', models.ImageField(blank=True, default='defaultimg.png', null=True, upload_to='', verbose_name='Team Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('height', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('string_no', models.CharField(choices=[('First String', 'First String'), ('Second String', 'Second String')], max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player', to='baseball.person')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='baseball.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_t1', models.IntegerField()),
                ('score_t2', models.IntegerField()),
                ('game_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date of Issuance')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='baseball.club')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='baseball.club')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='baseball.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='club',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.person'),
        ),
    ]
